language: node_js
node_js: 8

addons:
  firefox: latest

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0

notifications:
  irc:
    on_success: change
    channels: irc.mozilla.org#globalconsent
